
-- Generated by ORDS REST Data Services 25.4.0.r3441128
-- Schema: WKSP_ELEVATEORDG  Date: Thu Mar 05 05:04:54 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'elevate_ordg',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'inventory_module',
      p_base_path      => '/inventory/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'API for syncing inventory');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_inbound_stock',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_inbound_stock',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    -- Blob Conversion
    l_blob        BLOB;
    l_clob        CLOB;
    l_dest_offset INTEGER := 1;
    l_src_offset  INTEGER := 1;
    l_lang_ctx    INTEGER := dbms_lob.default_lang_ctx;
    l_warning     INTEGER;
    
    -- Data
    l_inbound_no   VARCHAR2(100);
    l_inbound_name VARCHAR2(255);
    l_sku          VARCHAR2(100);
    l_prod_name    VARCHAR2(255);
    l_qty_recv     NUMBER;
    l_qty_avail    NUMBER;
BEGIN
    -- 1. Convert Body to Text
    l_blob := :body;
    DBMS_LOB.CREATETEMPORARY(l_clob, TRUE);
    IF DBMS_LOB.GETLENGTH(l_blob) > 0 THEN
        DBMS_LOB.CONVERTTOCLOB(l_clob, l_blob, DBMS_LOB.LOBMAXSIZE, l_dest_offset, l_src_offset, nls_charset_id(''UTF8''), l_lang_ctx, l_warning);
    END IF;

    -- 2. Parse
    APEX_JSON.PARSE(l_clob);

    l_inbound_no   := APEX_JSON.GET_VARCHAR2(''inbound_order_no'');
    l_inbound_name := APEX_JSON.GET_VARCHAR2(''inbound_name'');
    l_sku          := APEX_JSON.GET_VARCHAR2(''sku'');
    l_p' || 'rod_name    := APEX_JSON.GET_VARCHAR2(''product_name'');
    l_qty_recv     := NVL(APEX_JSON.GET_NUMBER(''qty_received''), 0);
    l_qty_avail    := NVL(APEX_JSON.GET_NUMBER(''qty_available''), 0);

    -- 3. SAFETY BLOCK: Auto-Create Product
    -- We isolate this so if it fails (e.g. missing columns), the Stock insert still happens.
    BEGIN
        MERGE INTO ordg_products p 
        USING (SELECT l_sku as s FROM dual) src 
        ON (p.sku = src.s)
        WHEN NOT MATCHED THEN 
            -- We provide 0 for numeric defaults to prevent NULL errors
            INSERT (sku, product_name, total_available_qty) 
            VALUES (l_sku, l_prod_name, 0);
    EXCEPTION WHEN OTHERS THEN
        -- If product creation fails, ignore it and try to insert stock anyway
        NULL; 
    END;

    -- 4. Upsert Stock (The Main Goal)
    MERGE INTO inbound_stock s
    USING (SELECT l_inbound_no as o, l_sku as k FROM dual) src
    ON (s.inbound_order_no = src.o AND s.sku = sr' || 'c.k)
    
    WHEN MATCHED THEN
        UPDATE SET qty_received = l_qty_recv, qty_available = l_qty_avail
        
    WHEN NOT MATCHED THEN
        INSERT (inbound_order_no, inbound_name, sku, product_name, qty_received, qty_available)
        VALUES (l_inbound_no, l_inbound_name, l_sku, l_prod_name, l_qty_recv, l_qty_avail);

    -- 5. Commit and Response
    COMMIT; -- Explicitly commit to ensure data sticks
    
    :status := 200;
    HTP.P(''{"message": "Stock Synced", "sku": "'' || l_sku || ''"}'');
    
    DBMS_LOB.FREETEMPORARY(l_clob);

EXCEPTION WHEN OTHERS THEN
    :status := 400;
    HTP.P(''{"error": "'' || SQLERRM || ''"}'');
    IF l_clob IS NOT NULL THEN DBMS_LOB.FREETEMPORARY(l_clob); END IF;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_shipping_items',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_shipping_items',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    -- Standard variables for binary handling
    l_blob        BLOB;
    l_clob        CLOB;
    
    -- Variables for DBMS_LOB must be declared strictly
    l_dest_offset INTEGER := 1;
    l_src_offset  INTEGER := 1;
    l_lang_ctx    INTEGER := dbms_lob.default_lang_ctx;
    l_warning     INTEGER;
    l_amount      INTEGER := dbms_lob.lobmaxsize;
    
    -- Data variables
    l_ship_no     VARCHAR2(50);
    l_sku         VARCHAR2(100);
    l_asin        VARCHAR2(50);
    l_prod_name   VARCHAR2(255);
    l_qty         NUMBER;
    l_inbound_ref VARCHAR2(100);
    l_is_complete NUMBER := 0; 

    -- Helper Logging Procedure
    PROCEDURE log_info(p_rec_id IN VARCHAR2, p_msg IN VARCHAR2, p_err IN CLOB DEFAULT NULL) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO api_debug_logs (api_name, record_id, message, error_details)
        VALUES (''sync_shipping_items'', p_rec_id, p_msg, p_err);
        COMMIT;
    END;

BEGIN
    -- ' || '1. Convert Binary Body to Text
    l_blob := :body;
    DBMS_LOB.CREATETEMPORARY(l_clob, TRUE);
    IF DBMS_LOB.GETLENGTH(l_blob) > 0 THEN
        DBMS_LOB.CONVERTTOCLOB(l_clob, l_blob, l_amount, l_dest_offset, l_src_offset, nls_charset_id(''UTF8''), l_lang_ctx, l_warning);
    END IF;
    APEX_JSON.PARSE(l_clob);

    -- 2. Extract Data
    l_ship_no     := APEX_JSON.GET_VARCHAR2(''shipping_order_no'');
    l_sku         := APEX_JSON.GET_VARCHAR2(''sku'');
    l_asin        := APEX_JSON.GET_VARCHAR2(''asin'');
    l_prod_name   := APEX_JSON.GET_VARCHAR2(''product_name'');
    l_qty         := NVL(APEX_JSON.GET_NUMBER(''qty_shipped''), 0);
    l_inbound_ref := APEX_JSON.GET_VARCHAR2(''inbound_source_number'');
    l_is_complete := NVL(APEX_JSON.GET_NUMBER(''mark_complete''), 0); 

    log_info(l_ship_no || '' - '' || l_sku, ''Processing Item'');

    IF l_sku IS NOT NULL THEN
        -- 3. SAFETY: Ensure Product Exists (Prevent FK Error)
        BEGIN
            MERGE INTO ordg_prod' || 'ucts p 
            USING (SELECT l_sku as s FROM dual) src 
            ON (p.sku = src.s)
            WHEN NOT MATCHED THEN 
                INSERT (sku, product_name, total_available_qty) 
                VALUES (l_sku, l_prod_name, 0);
        EXCEPTION WHEN OTHERS THEN
            log_info(l_ship_no, ''Product Auto-Create Warning'', SQLERRM);
        END;

        -- 4. THE FIX: Use MERGE instead of INSERT
        -- This handles duplicates gracefully without crashing.
    --     MERGE INTO shipping_order_items t
    --     USING (SELECT l_ship_no as o, l_sku as s FROM dual) src
    --     ON (t.shipping_order_no = src.o AND t.sku = src.s)
        
    --     WHEN MATCHED THEN
    --         UPDATE SET 
    --             qty_shipped = l_qty,
    --             product_name = l_prod_name,
    --             inbound_source_number = l_inbound_ref,
    --             asin = l_asin
                
    --     WHEN NOT MATCHED THEN
    --         INSERT (shipping_' || 'order_no, sku, asin, product_name, qty_shipped, inbound_source_number)
    --         VALUES (l_ship_no, l_sku, l_asin, l_prod_name, l_qty, l_inbound_ref);
            
    --     log_info(l_ship_no, ''Item Saved Successfully'');
    -- END IF;
MERGE INTO shipping_order_items t
        USING (
            SELECT 
                l_ship_no as o, 
                l_sku as s, 
                l_inbound_ref as i 
            FROM dual
        ) src
        ON (
            t.shipping_order_no = src.o 
            AND t.sku = src.s 
            AND NVL(t.inbound_source_number, ''X'') = NVL(src.i, ''X'') 
        )
        
        WHEN MATCHED THEN
            UPDATE SET 
                qty_shipped = l_qty,
                product_name = l_prod_name,
                asin = l_asin
                -- MAKE SURE inbound_source_number IS COMPLETELY REMOVED FROM HERE!
                
        WHEN NOT MATCHED THEN
            INSERT (shipping_order_no, sku, asin, product_nam' || 'e, qty_shipped, inbound_source_number)
            VALUES (l_ship_no, l_sku, l_asin, l_prod_name, l_qty, l_inbound_ref);
     log_info(l_ship_no, ''Item Saved Successfully'');
    END IF;

    -- 5. Update Parent Order Status
    UPDATE shipping_orders
    SET 
        inbound_number = COALESCE(inbound_number, l_inbound_ref), 
        details_fetched = CASE WHEN l_is_complete = 1 THEN 1 ELSE details_fetched END
    WHERE order_no = l_ship_no;

    IF l_is_complete = 1 THEN
        log_info(l_ship_no, ''Order Marked Complete'');
    END IF;

    -- 6. COMMIT ensures data is saved
    COMMIT; 
    
    :status := 200;
    HTP.P(''{"message": "Item Processed", "sku": "'' || l_sku || ''"}'');
    DBMS_LOB.FREETEMPORARY(l_clob);

EXCEPTION WHEN OTHERS THEN
    -- If we get here, it logs the REAL error so we know why it failed.
    log_info(l_ship_no, ''CRITICAL FAILURE'', SQLERRM);
    ROLLBACK;
    :status := 400;
    HTP.P(''{"error": "'' || SQLERRM || ''"}'');
    IF l_clo' || 'b IS NOT NULL THEN DBMS_LOB.FREETEMPORARY(l_clob); END IF;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_product',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_product',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    -- Standard Variables
    l_blob        BLOB;
    l_clob        CLOB;
    l_dest_offset INTEGER := 1;
    l_src_offset  INTEGER := 1;
    l_lang_ctx    INTEGER := dbms_lob.default_lang_ctx;
    l_warning     INTEGER;
    
    -- Data Variables
    l_sku         VARCHAR2(100);
    l_asin        VARCHAR2(100);
    l_name        VARCHAR2(4000);
    l_img         VARCHAR2(4000);
    l_cond        VARCHAR2(100);
    l_dims        VARCHAR2(100);
    l_unit        VARCHAR2(50);
    l_pack        VARCHAR2(100);
    l_qty         NUMBER;
BEGIN
    -- 1. Get the binary body
    l_blob := :body;

    -- 2. Initialize a temporary CLOB (Text storage)
    DBMS_LOB.CREATETEMPORARY(l_clob, TRUE);

    -- 3. Convert Binary (BLOB) to Text (CLOB) - The Safety Bridge
    IF DBMS_LOB.GETLENGTH(l_blob) > 0 THEN
        DBMS_LOB.CONVERTTOCLOB(
            dest_lob     => l_clob,
            src_blob     => l_blob,
            amount       => DBMS_LOB.LOBMAXSIZE,
  ' || '          dest_offset  => l_dest_offset,
            src_offset   => l_src_offset,
            blob_csid    => nls_charset_id(''UTF8''),
            lang_context => l_lang_ctx,
            warning      => l_warning
        );
    END IF;

    -- 4. Parse the CLOB (This is guaranteed to work)
    APEX_JSON.PARSE(l_clob);

    -- 5. Extract Values
    l_sku  := APEX_JSON.GET_VARCHAR2(''sku'');
    l_asin := APEX_JSON.GET_VARCHAR2(''asin'');
    l_name := UTL_I18N.UNESCAPE_REFERENCE(APEX_JSON.GET_VARCHAR2(''product_name''));
    l_img  := APEX_JSON.GET_VARCHAR2(''image_url'');
    l_cond := APEX_JSON.GET_VARCHAR2(''product_condition'');
    l_dims := APEX_JSON.GET_VARCHAR2(''dimensions'');
    l_unit := APEX_JSON.GET_VARCHAR2(''dimension_unit'');
    l_pack := APEX_JSON.GET_VARCHAR2(''packing_type'');
    l_qty  := APEX_JSON.GET_NUMBER(''total_available_qty'');

    -- 6. Merge Logic (Upsert)
    MERGE INTO ordg_products p
    USING (SELECT l_sku as sku FROM dual) src
    ON (p.sku =' || ' src.sku)
    WHEN MATCHED THEN
        UPDATE SET asin = l_asin, product_name = l_name, image_url = l_img,
                   product_condition = l_cond, dimensions = l_dims,
                   dimension_unit = l_unit, packing_type = l_pack,
                   total_available_qty = l_qty
    WHEN NOT MATCHED THEN
        INSERT (sku, asin, product_name, image_url, product_condition, 
                dimensions, dimension_unit, packing_type, total_available_qty)
        VALUES (l_sku, l_asin, l_name, l_img, l_cond, 
                l_dims, l_unit, l_pack, l_qty);

    -- 7. Response
    :status := 200;
    HTP.P(''{"message": "Success", "sku": "'' || l_sku || ''"}'');

    -- Cleanup
    DBMS_LOB.FREETEMPORARY(l_clob);

EXCEPTION WHEN OTHERS THEN
    :status := 400;
    HTP.P(''{"error": "'' || SQLERRM || ''"}'');
    IF l_clob IS NOT NULL THEN
        DBMS_LOB.FREETEMPORARY(l_clob);
    END IF;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'pending_shipping_orders',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'pending_shipping_orders',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT order_no 
FROM shipping_orders 
WHERE details_fetched = 0 
   OR details_fetched IS NULL');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'complete_shipping_order',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'complete_shipping_order',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_blob    BLOB;
    l_clob    CLOB;
    l_order   VARCHAR2(100);
    l_inbound VARCHAR2(100);
BEGIN
    -- Boilerplate to convert JSON body
    l_blob := :body;
    DBMS_LOB.CREATETEMPORARY(l_clob, TRUE);
    IF DBMS_LOB.GETLENGTH(l_blob) > 0 THEN
        DBMS_LOB.CONVERTTOCLOB(l_clob, l_blob, DBMS_LOB.LOBMAXSIZE, 1, 1, nls_charset_id(''UTF8''), dbms_lob.default_lang_ctx, dbms_lob.lobmaxsize);
    END IF;
    APEX_JSON.PARSE(l_clob);

    l_order   := APEX_JSON.GET_VARCHAR2(''order_no'');
    l_inbound := APEX_JSON.GET_VARCHAR2(''inbound_number'');

    -- Update the status
    UPDATE shipping_orders
    SET details_fetched = 1,
        inbound_number = l_inbound
    WHERE order_no = l_order;

    :status := 200;
    HTP.P(''{"message": "Order Marked Complete"}'');
    DBMS_LOB.FREETEMPORARY(l_clob);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_inbound_shipments',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_inbound_shipments',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    -- Blob/Clob Conversion Variables
    l_blob         BLOB;
    l_clob         CLOB;
    l_dest_offset INTEGER := 1;
    l_src_offset  INTEGER := 1;
    l_lang_ctx    INTEGER := dbms_lob.default_lang_ctx;
    l_warning     INTEGER;
    
    -- Data Variables
    l_order_no       VARCHAR2(100);
    l_order_name     VARCHAR2(255);
    l_status         VARCHAR2(50);
    l_date_created   VARCHAR2(50); 
    l_date_received  VARCHAR2(50);
    l_comment        VARCHAR2(4000);
BEGIN
    -- 1. Convert Binary to Text
    l_blob := :body;
    DBMS_LOB.CREATETEMPORARY(l_clob, TRUE);
    IF DBMS_LOB.GETLENGTH(l_blob) > 0 THEN
        DBMS_LOB.CONVERTTOCLOB(l_clob, l_blob, DBMS_LOB.LOBMAXSIZE, l_dest_offset, l_src_offset, nls_charset_id(''UTF8''), l_lang_ctx, l_warning);
    END IF;

    -- 2. Parse
    APEX_JSON.PARSE(l_clob);

    -- 3. Extract Data
    l_order_no      := APEX_JSON.GET_VARCHAR2(''order_no'');
    l_order_name    := APEX_JSON.GET_VARCHAR2(''order_' || 'name'');
    l_status        := APEX_JSON.GET_VARCHAR2(''status''); 
    l_date_created  := APEX_JSON.GET_VARCHAR2(''date_created'');
    l_date_received := APEX_JSON.GET_VARCHAR2(''date_received'');
    l_comment       := APEX_JSON.GET_VARCHAR2(''client_comment'');

    -- 4. Upsert into Inbound Shipments
    MERGE INTO inbound_shipments t
    USING (SELECT l_order_no as order_no FROM dual) src
    ON (t.order_no = src.order_no)
    
    WHEN MATCHED THEN
        UPDATE SET 
            status = l_status, 
            -- FIX: Only convert to date if it''s NOT ''pending''
            date_received = CASE 
                                WHEN LOWER(l_date_received) = ''pending'' THEN NULL 
                                ELSE TO_DATE(l_date_received, ''DD/MM/YYYY HH24:MI:SS'') 
                            END,
            client_comment = l_comment
            
    WHEN NOT MATCHED THEN
        INSERT (order_no, order_name, status, date_created, date_received, client_comment)
   ' || '     VALUES (
            l_order_no, 
            l_order_name, 
            l_status, 
            TO_DATE(l_date_created, ''DD/MM/YYYY HH24:MI:SS''), 
            -- FIX: Handle ''pending'' on initial insert too
            CASE 
                WHEN LOWER(l_date_received) = ''pending'' THEN NULL 
                ELSE TO_DATE(l_date_received, ''DD/MM/YYYY HH24:MI:SS'') 
            END, 
            l_comment
        );

    :status := 200;
    HTP.P(''{"message": "Shipment Synced", "id": "'' || l_order_no || ''"}'');
    DBMS_LOB.FREETEMPORARY(l_clob);

EXCEPTION WHEN OTHERS THEN
    :status := 400;
    HTP.P(''{"error": "'' || SQLERRM || ''"}'');
    IF l_clob IS NOT NULL THEN DBMS_LOB.FREETEMPORARY(l_clob); END IF;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_shipping_orders',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'sync_shipping_orders',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    -- Standard Variables
    l_blob        BLOB;
    l_clob        CLOB;
    l_dest_offset INTEGER := 1;
    l_src_offset  INTEGER := 1;
    l_lang_ctx    INTEGER := dbms_lob.default_lang_ctx;
    l_warning     INTEGER;
    l_amount      INTEGER := dbms_lob.lobmaxsize;
    
    -- Data Variables
    l_order_no       VARCHAR2(50);
    l_order_name     VARCHAR2(100);
    l_status         VARCHAR2(50);
    l_total_qty      NUMBER;
    l_total_sku      NUMBER;
    l_platform       VARCHAR2(50);
    l_comment        CLOB;
    l_date_created   VARCHAR2(50);
    l_date_shipped   VARCHAR2(50);

    -- Helper Procedure to Log safely (Saves even if main logic fails)
    PROCEDURE log_info(p_rec_id IN VARCHAR2, p_msg IN VARCHAR2, p_err IN CLOB DEFAULT NULL) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO api_debug_logs (api_name, record_id, message, error_details)
        VALUES (''sync_shipping_orders'', p_rec_id, p_msg, p_err);
        C' || 'OMMIT;
    END;

BEGIN
    -- 1. Convert Body
    l_blob := :body;
    DBMS_LOB.CREATETEMPORARY(l_clob, TRUE);
    IF DBMS_LOB.GETLENGTH(l_blob) > 0 THEN
        DBMS_LOB.CONVERTTOCLOB(l_clob, l_blob, l_amount, l_dest_offset, l_src_offset, nls_charset_id(''UTF8''), l_lang_ctx, l_warning);
    END IF;

    -- 2. Parse
    APEX_JSON.PARSE(l_clob);

    l_order_no     := APEX_JSON.GET_VARCHAR2(''order_no'');
    
    -- Log Start
    log_info(l_order_no, ''Started processing header'');

    l_order_name   := APEX_JSON.GET_VARCHAR2(''order_name'');
    l_status       := APEX_JSON.GET_VARCHAR2(''status'');
    l_total_qty    := APEX_JSON.GET_NUMBER(''total_quantity'');
    l_total_sku    := APEX_JSON.GET_NUMBER(''total_sku'');
    l_platform     := APEX_JSON.GET_VARCHAR2(''selling_platform'');
    l_comment      := APEX_JSON.GET_VARCHAR2(''client_comment'');
    l_date_created := APEX_JSON.GET_VARCHAR2(''date_created'');
    l_date_shipped := APEX_JSON.GET_VARCHAR2(''date_shipped'');
' || '
    -- 3. Upsert Logic
    MERGE INTO shipping_orders t
    USING (SELECT l_order_no as order_no FROM dual) src
    ON (t.order_no = src.order_no)
    
    WHEN MATCHED THEN
        UPDATE SET 
            selling_platform = l_platform,  -- <--- Updates the empty field
            status = l_status               -- Updates status while we are at it
            
    WHEN NOT MATCHED THEN
        INSERT (
            order_no, order_name, status, total_quantity, total_sku, 
            selling_platform, client_comment, date_created, date_shipped, 
            details_fetched
        )
        VALUES (
            l_order_no, l_order_name, l_status, l_total_qty, l_total_sku, 
            l_platform, l_comment, 
            TO_TIMESTAMP(l_date_created, ''DD/MM/YYYY HH24:MI:SS''), 
            TO_TIMESTAMP(l_date_shipped, ''DD/MM/YYYY HH24:MI:SS''),
            0
        );

    -- 4. Response & Log Success
    IF SQL%ROWCOUNT = 0 THEN
        log_info(l_order_no, ''Sk' || 'ipped: Order already exists'');
        :status := 200;
        HTP.P(''{"message": "Skipped", "id": "'' || l_order_no || ''"}'');
    ELSE
        log_info(l_order_no, ''Success: Created new order'');
        :status := 201; 
        HTP.P(''{"message": "Created", "id": "'' || l_order_no || ''"}'');
    END IF;
    
    DBMS_LOB.FREETEMPORARY(l_clob);

EXCEPTION WHEN OTHERS THEN
    -- Log Error
    log_info(l_order_no, ''CRITICAL FAILURE'', SQLERRM);
    
    :status := 400;
    HTP.P(''{"error": "'' || SQLERRM || ''"}'');
    IF l_clob IS NOT NULL THEN DBMS_LOB.FREETEMPORARY(l_clob); END IF;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'last_shipping_sync',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'last_shipping_sync',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT TO_CHAR(MAX(date_created), ''DD/MM/YYYY HH24:MI:SS'') as max_date 
FROM shipping_orders');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'inventory_module',
      p_pattern        => 'missing_data_checks',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'inventory_module',
      p_pattern        => 'missing_data_checks',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 10000,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT order_no 
FROM shipping_orders 
WHERE selling_platform IS NULL 
   OR selling_platform = ''''');


COMMIT;

END;